### ISSUE TITLE
Any way to hide dropdown menu on click outside?

### ISSUE THREAD

**Issue by slash686** [Snapp-X/flex_dropdown#1]
Hi, thanks for the package. It seems to me that there is no way to hide open dropdown menu on click outside. I am missing something?

**Comment by kassfir** [comment]
Perhaps a fork should be created (because it doesn't look like the package is maintained), but for the time being you could probably use the `TapRegion` class. Using its `onTapOutside` property to detect clicks, you could then call a function to close the dropdown. 

Reference: https://api.flutter.dev/flutter/widgets/TapRegion-class.html

**Comment by payam-zahedi** [comment]
I'll look into this later

but as a proposal you can put your menu on a gesture detector and checkout the out side clicks

I'm not sure but it should work

**Comment by payam-zahedi** [comment]
Hi @slash686 and @kassfir,

I’ve resolved this issue by adding a new property to the widget: dismissOnTapOutside. Enabling this property allows the menu to close when clicking outside of it.

Let me know if you have any feedback!
